### ISSUE TITLE
linker error because nonexistent python3

### ISSUE THREAD

**Issue by zigastegu** [carrotIndustries/pluto-fw#17]
On Ubuntu (i tried 18.04.1 lts and 16.04.1 lts) python3 is not accessible on /usr/bin/env
To make it work I changed
**#!/usr/bin/env python3**
to
**#!/usr/bin/python3**

**Comment by luftek** [comment]
Use: msp430-gcc  version 4.0.1.0 by Red Hat

**Comment by luftek** [comment]
Use: msp430-gcc  version 4.0.1.0 by Red Hat

**Comment by zigastegu** [comment]
Should we add a check in Makefile if python3 is present on certaing path?
