### ISSUE TITLE
include mbedtls in this repository

### ISSUE THREAD

**Issue by hackrid** [carrotIndustries/pluto-fw#2]
add the needed files to this repo to get past a "make" in the sim/ directory

**Comment by carrotIndustries** [comment]
The simulator is supposed to use mbedtls provided by your linux distribution. See https://github.com/carrotIndustries/pluto-fw#dependencies-for-simulator

**Comment by hackrid** [comment]
what distro does provide mbedtls ?
what did you use for developement?

ubuntu 14.04 is a horror since there seem to be dependencies to gtk+3.12.
edit: I got it working in 16.04 with much less trouble...

**Comment by hackrid** [comment]
since you include the sha.h https://github.com/carrotIndustries/pluto-fw/tree/master/common/svc/otp/mbedtls/include/mbedtls

you should also include the aes.h or is this not right?

**Comment by carrotIndustries** [comment]
https://github.com/carrotIndustries/pluto-fw#included-third-party-software
I only need sha1 since AES is provieded by the MSP430 peripherals.

**Comment by hackrid** [comment]
strange... I still had to provide the aes.h when compiling the simulator
