### ISSUE TITLE
Setting countdowns over 3 hours results in display weirdness

### ISSUE THREAD

**Issue by cculpepper** [carrotIndustries/pluto-fw#8]
When setting a countdown of over 3 hours, the display displays incorrect numbers.
When incrementing hours, the display will go: 03:00:00 => 94:17:60. 
When exiting the setting menu, after pressing increment the correct number of times, the alarm functions correctly. 
I have yet to look into the code to figure out why

**Comment by carrotIndustries** [comment]
Fixed in Commit bcb6bf19c8d2ca05635fa45a256615f607ad730f
